# Generated by Django 2.2.5 on 2019-10-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191024_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('P', 'Prevenção e Cuidado'), ('De', 'Denuncias'), ('Do', 'Doações'), ('B', 'Blog')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
