# Generated by Django 2.2.5 on 2019-11-21 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('denuncias', '0002_auto_20191023_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('R', 'Denúncia Registrada'), ('A', 'Aguardando Resposta'), ('C', 'Denúncia Concluída'), ('E', 'Denúncia Excluída')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='status_obs',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='denuncia',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
