# Generated by Django 2.2.5 on 2019-11-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0004_auto_20191121_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('R', 'Denúncia Registrada'), ('A', 'Aguardando Resposta'), ('C', 'Denúncia Concluída'), ('E', 'Denúncia Excluída')], default='Denúncia Registrada', max_length=1),
        ),
    ]
